Resources:
  VPCB9E5F0B4:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: eks-dev
    Metadata:
      aws:cdk:path: VPC/VPC/Resource
  VPCekspublicSubnet1Subnet93047359:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: eks-public
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: VPC/VPC/eks-publicSubnet1
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet1/Subnet
  VPCekspublicSubnet1RouteTable5A8B0FF9:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: VPC/VPC/eks-publicSubnet1
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet1/RouteTable
  VPCekspublicSubnet1RouteTableAssociationB92D8D79:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCekspublicSubnet1RouteTable5A8B0FF9
      SubnetId:
        Ref: VPCekspublicSubnet1Subnet93047359
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet1/RouteTableAssociation
  VPCekspublicSubnet1DefaultRoute1CE7847D:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCekspublicSubnet1RouteTable5A8B0FF9
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: VPCIGWB7E252D3
    DependsOn:
      - VPCVPCGW99B986DC
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet1/DefaultRoute
  VPCekspublicSubnet1EIP4005032F:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: VPC/VPC/eks-publicSubnet1
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet1/EIP
  VPCekspublicSubnet1NATGateway911D14F3:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId:
        Ref: VPCekspublicSubnet1Subnet93047359
      AllocationId:
        Fn::GetAtt:
          - VPCekspublicSubnet1EIP4005032F
          - AllocationId
      Tags:
        - Key: Name
          Value: VPC/VPC/eks-publicSubnet1
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet1/NATGateway
  VPCekspublicSubnet2Subnet01EB5129:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: eks-public
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: VPC/VPC/eks-publicSubnet2
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet2/Subnet
  VPCekspublicSubnet2RouteTable5B80C491:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: VPC/VPC/eks-publicSubnet2
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet2/RouteTable
  VPCekspublicSubnet2RouteTableAssociation421A0A46:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCekspublicSubnet2RouteTable5B80C491
      SubnetId:
        Ref: VPCekspublicSubnet2Subnet01EB5129
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet2/RouteTableAssociation
  VPCekspublicSubnet2DefaultRouteE0F72480:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCekspublicSubnet2RouteTable5B80C491
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: VPCIGWB7E252D3
    DependsOn:
      - VPCVPCGW99B986DC
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet2/DefaultRoute
  VPCekspublicSubnet2EIPE671A43A:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: VPC/VPC/eks-publicSubnet2
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet2/EIP
  VPCekspublicSubnet2NATGateway9D2990A2:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId:
        Ref: VPCekspublicSubnet2Subnet01EB5129
      AllocationId:
        Fn::GetAtt:
          - VPCekspublicSubnet2EIPE671A43A
          - AllocationId
      Tags:
        - Key: Name
          Value: VPC/VPC/eks-publicSubnet2
    Metadata:
      aws:cdk:path: VPC/VPC/eks-publicSubnet2/NATGateway
  VPCeksprivateSubnet1SubnetB9D69E47:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: aws-cdk:subnet-name
          Value: eks-private
        - Key: aws-cdk:subnet-type
          Value: Private
        - Key: Name
          Value: VPC/VPC/eks-privateSubnet1
    Metadata:
      aws:cdk:path: VPC/VPC/eks-privateSubnet1/Subnet
  VPCeksprivateSubnet1RouteTable489EE95D:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: VPC/VPC/eks-privateSubnet1
    Metadata:
      aws:cdk:path: VPC/VPC/eks-privateSubnet1/RouteTable
  VPCeksprivateSubnet1RouteTableAssociation44B7BB7C:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCeksprivateSubnet1RouteTable489EE95D
      SubnetId:
        Ref: VPCeksprivateSubnet1SubnetB9D69E47
    Metadata:
      aws:cdk:path: VPC/VPC/eks-privateSubnet1/RouteTableAssociation
  VPCeksprivateSubnet1DefaultRoute8DEECC3A:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCeksprivateSubnet1RouteTable489EE95D
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: VPCekspublicSubnet1NATGateway911D14F3
    Metadata:
      aws:cdk:path: VPC/VPC/eks-privateSubnet1/DefaultRoute
  VPCeksprivateSubnet2Subnet3395C91D:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: aws-cdk:subnet-name
          Value: eks-private
        - Key: aws-cdk:subnet-type
          Value: Private
        - Key: Name
          Value: VPC/VPC/eks-privateSubnet2
    Metadata:
      aws:cdk:path: VPC/VPC/eks-privateSubnet2/Subnet
  VPCeksprivateSubnet2RouteTable93FA4E5E:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: VPC/VPC/eks-privateSubnet2
    Metadata:
      aws:cdk:path: VPC/VPC/eks-privateSubnet2/RouteTable
  VPCeksprivateSubnet2RouteTableAssociation4BD4D44B:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCeksprivateSubnet2RouteTable93FA4E5E
      SubnetId:
        Ref: VPCeksprivateSubnet2Subnet3395C91D
    Metadata:
      aws:cdk:path: VPC/VPC/eks-privateSubnet2/RouteTableAssociation
  VPCeksprivateSubnet2DefaultRouteF4DD980C:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCeksprivateSubnet2RouteTable93FA4E5E
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: VPCekspublicSubnet2NATGateway9D2990A2
    Metadata:
      aws:cdk:path: VPC/VPC/eks-privateSubnet2/DefaultRoute
  VPCIGWB7E252D3:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: eks-dev
    Metadata:
      aws:cdk:path: VPC/VPC/IGW
  VPCVPCGW99B986DC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      InternetGatewayId:
        Ref: VPCIGWB7E252D3
    Metadata:
      aws:cdk:path: VPC/VPC/VPCGW
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02OQQuCQBCFf0v3dSuFoGNIhJdYNLzGuk40qbvhziYi/ffWrOz0vnk83ryQRxu+WsjOBqqsghoLPmQkVcW8dQYV8iG/KxZfdC5iJlxRo8pcoYFGb6bUOIKTLGqY/dnbWWsUSkKjf+ER9okY5SjpIAk62TPR4sPjXJxogtbzNzAt+Vw78lOvDWh6shSsca169/5zbHSJ4+cnEz1djV5GfMvX0eJmEYPWacIGeDrpC9PUuvMPAQAA
    Metadata:
      aws:cdk:path: VPC/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

